# Generated by Django 4.2.9 on 2024-01-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="img/", verbose_name="Изображение"
            ),
        ),
    ]
