# Generated by Django 4.2.9 on 2024-01-08 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Контакт", "verbose_name_plural": "Контакты"},
        ),
    ]
